# Generated by Django 4.1.7 on 2023-02-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=255)),
                ('ucontact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'usertb',
            },
        ),
    ]
